{% set name = "openskill" %}
{% set version = "6.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openskill-{{ version }}.tar.gz
  sha256: 7241f6dcfffb3aa1be339fda479e608f35f127cce764e27df90a460733606d1d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ~=3.10
    - setuptools
  run:
    - python ~=3.10

test:
  imports:
    - openskill
    - openskill.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenDebates/openskill.py
  summary: License-free implementation of Weng-Lin Bayesian ranking
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
