{% set name = "openskill" %}
{% set version = "6.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openskill-{{ version }}.tar.gz
  sha256: eee2d0b3c1648663a480cf4680654dfd12bdc749a96d611b1904e191f2632f62

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pdm-backend
    - pip
    - python ~=3.8
  run:
    - python ~=3.8

test:
  source_files:
    - tests
  imports:
    - openskill
    - openskill.models
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest ~=7.3

about:
  home: https://github.com/OpenDebates/openskill.py
  summary: License-free implementation of Weng-Lin Bayesian ranking
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
