schema_version: 1

context:
  name: openskill
  version: "6.2.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/openskill-${{ version }}.tar.gz
  sha256: 817c5192aaed489697a1703fc2a3f9ea84b4487b09d0c27fd270a04f08f13d67

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - mypy
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - openskill
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  summary: License-free implementation of Weng-Lin Bayesian ranking
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/vivekjoshy/openskill.py

extra:
  recipe-maintainers:
    - thewchan
